version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your Vite React app's Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Serve React on localhost:3000

  backend:
    build:
      context: ./springboot  # Path to your Spring Boot app's Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
