"""Initial migration3

Revision ID: 779ffe270308
Revises: ee8dca299b69
Create Date: 2024-11-08 14:22:15.523568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779ffe270308'
down_revision = 'ee8dca299b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_contents', schema=None) as batch_op:
        batch_op.drop_column('week_number')

    # ### end Alembic commands ###
