"""Added a details table - for each lessoncontent there will be a details page

Revision ID: d43ce0ea6e70
Revises: 0dc3f130fa0e
Create Date: 2024-11-19 12:11:27.412439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43ce0ea6e70'
down_revision = '0dc3f130fa0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('paragraph1', sa.String(), nullable=True),
    sa.Column('paragraph2', sa.String(), nullable=True),
    sa.Column('heading1', sa.String(), nullable=True),
    sa.Column('sentence1', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_details_lesson_content_id'), ['lesson_content_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_details_lesson_content_id'))

    op.drop_table('details')
    # ### end Alembic commands ###
