"""Removing the details model - the actual contents will be hardcoded from frontend

Revision ID: fceb2927bfa5
Revises: d43ce0ea6e70
Create Date: 2024-11-20 13:21:01.830008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fceb2927bfa5'
down_revision = 'd43ce0ea6e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.drop_index('ix_details_lesson_content_id')

    op.drop_table('details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_content_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paragraph1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paragraph2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('heading1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sentence1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_contents.id'], name='details_lesson_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='details_pkey')
    )
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.create_index('ix_details_lesson_content_id', ['lesson_content_id'], unique=False)

    # ### end Alembic commands ###
